### ISSUE TITLE
When in AP mode enable HTTP redirect

### ISSUE THREAD

**Issue by Rutger798** [thekr1s/esp8266_wordclock#17]
This way when connecting to the clock for the first time a popup will show to enter the credentials

**Comment by thekr1s** [comment]
I have tried this. I think it was called 'captive dns'. But that did not work well back then. It is good to give it a retry.

**Comment by Rutger798** [comment]
Voor de Cloudia heet het HTTP redirect;), maar bedankt voor de tip ik ga nog even verder zoeken op "captive dns"
Voor de arduino ESP is het wel gelukt: https://github.com/tzapu/WiFiManager
En iemand heeft het volgens mij aan de praat (wel met een nieuwe versie van esp-open-rtos: https://github.com/maximkulkin/esp-wifi-config

**Comment by thekr1s** [comment]
Er zit al een dns servertje in de woordklok. Als je die op elk request zijn eigennipadres laat retourneren is het volgens mij al goed. Was volgens mij een probleem dat hij omkwam in de requests ofzo... Daarom laat ik alleen zijn ip retouerneren als er woordklok in de naam staat oid.

**Comment by Rutger798** [comment]
Zag inderdaad wel een hoop van de zelfde code, maar ik zie dat https://github.com/maximkulkin/esp-wifi-config gebruikt maakt van een nieuwe versie van esp-open-rtos......
En ik zie dat er een patch is gemaakt in de dhcpserver.

**Comment by Rutger798** [comment]
Haha Ik heb het esp-open-rtos geupdate naar de laatste versie maar er gaat nog iets mis met de aansturing van het display. maar daar ga ik een ander keertje mee klooien

**Comment by thekr1s** [comment]
Oh cool! Heb je veel moeten doen? Er zitten volgens mij een paar hacks in het OS. Bijv om eigen ip adrs te achterhalen..

**Comment by Rutger798** [comment]
mwa viel wel mee, en veel patches zijn niet meer nodig door de nieuwe versie. maar bijna alles werkt alleen de ledstip wordt niet correct aangestuurd, de kleur klopt niet en hij zit er soms een letter naast.... gaat er bij jou dan toevallig een lampje branden ?

**Comment by thekr1s** [comment]
Klinkt als dat de timing niet gehaald wordt. Als ik het goed heb wordt de timing geregeld via spi. Dan zou er iets in de spi driver zitten. 
Als je het anders pusht, wil ik er wel even naar kijken...

**Comment by Rutger798** [comment]
Het OS is geupdate in https://github.com/thekr1s/esp8266_wordclock/pull/18 na de merge ga ik het nog een keer proberen.

**Comment by Rutger798** [comment]
Issue is solved in https://github.com/thekr1s/esp8266_wordclock/pull/32

**Comment by Rutger798** [comment]
Retry:
Get Idle time by low prio task
?Sem between setting save and irq delay?
split wifi cfg into webpage and wificfg
retry captive DNS
