### ISSUE TITLE
Personalize via system config web page

### ISSUE THREAD

**Issue by thekr1s** [thekr1s/esp8266_wordclock#2]
Currently personalisation for rutger and robert is done via SSID. Personal stuff must be removed from the archive

**Comment by Rutger798** [comment]
dus dan worden de volgende items instelbaar:
hierbenik: URL, port, request
ota-tftp: URL, port
wel of geen perfect imperfections

Alleen de "he lise en evi wacht even" weet ik even niet iets generiek voor te verzinnen

**Comment by thekr1s** [comment]
Oh cool dat je dit oppakt. Was ook het eerste wat ik wilde aanpakken.!

De optie "wel of geen perfect imperfections" is onder protest!!

**Comment by Rutger798** [comment]
Haha dan moet je protesteren tegen Suzanne...
Maar heb ook al een pull request gestuurd ;)
