### ISSUE TITLE
OTA firmware update crashes

### ISSUE THREAD

**Issue by thekr1s** [thekr1s/esp8266_wordclock#35]
Looks like since the RTOS is updated the software update fails.
Investigations up to now show chaos. Crashes at different locations. Looks like head / stack problems

**Comment by Rutger798** [comment]
Please try to reproduct in captive DNS

**Comment by thekr1s** [comment]
It also reproduces in that Captive DNS branch

**Comment by Rutger798** [comment]
Dit lag aan de manier hoe jij flashed? (dus mag die dicht?)
